### ISSUE TITLE
[Bug]: Please ensure that the class definition "Qruto\Wave\Events\SsePingEvent" of the object you are trying to operate on was loaded _before_ unserialize()

### ISSUE THREAD

**Issue by Anjaxs** [qruto/laravel-wave#70]
### What happened?

Found this error in the log, hope to fix it

### How to reproduce the bug

```
{
  "exception": "[object] (Error(code: 0): The script tried to call a method on an incomplete object. Please ensure that the class definition \"Qruto\\Wave\\Events\\SsePingEvent\" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition at /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php:76)
[stacktrace]
#0 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php(76): method_exists()
#1 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Broadcasting\\BroadcastEvent->handle()
#2 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#4 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#5 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#6 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#7 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#8 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#10 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\\Bus\\Dispatcher->dispatchNow()
#11 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#12 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(126): Illuminate\\Pipeline\\Pipeline->then()
#14 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#15 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\\Queue\\CallQueuedHandler->call()
#16 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(439): Illuminate\\Queue\\Jobs\\Job->fire()
#17 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\\Queue\\Worker->process()
#18 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\\Queue\\Worker->runJob()
#19 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(138): Illuminate\\Queue\\Worker->daemon()
#20 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(121): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#21 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#22 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#24 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#25 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#26 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#27 /www/wwwroot/homemassage/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#28 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\\Component\\Console\\Command\\Command->run()
#29 /www/wwwroot/homemassage/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#30 /www/wwwroot/homemassage/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#31 /www/wwwroot/homemassage/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#32 /www/wwwroot/homemassage/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#33 /www/wwwroot/homemassage/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#34 {main}
"
}
```

### Package Version

0.9.1

### PHP Version

8.1.27

### Laravel Version

10.48.10

### Which operating systems does with happen with?

Linux

**Comment by slavarazum** [comment]
Could you please provide an extended context when exactly this issue occurs?

**Comment by slavarazum** [comment]
If the problem persists, please open a new issue with a detailed explanation and steps to reproduce it.
